### PR TITLE
Apply forge format and removes prettier

### PR DESCRIPTION
**Pull request by magnetto90**

### CODE REVIEW

**Review by EperezOk — COMMENTED** [review]
I personally don't like having the `.vscode` folder pushed to Github, but just personal preference.

**Comment by magnetto90** [comment]
> I personally don't like having the `.vscode` folder pushed to Github, but just personal preference.

My idea is that we all use the same formatter and extensions for this workspace. What do you think?

**Comment by EperezOk** [comment]
Regarding IDE extensions, I believe everyone should use what they feel more comfortable with (unless there's a good reason to enforce one in particular).

Regarding the linter/formatter, it can be run/applied with a Github action.

**Comment by magnetto90** [comment]
@EperezOk removed `.vscode` folder, but added a check in the workflow to verify that the code is well formatted, it will depend on each dev to run `forge fmt` before each commit.

**Pull request merged**
